/*$file${tmp::smhsmtst.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
 * File:  ${tmp::smhsmtst.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${tmp::smhsmtst.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${smhsmtst::SmHsmTst} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${smhsmtst::SmHsmTst} ....................................................*/

/*${smhsmtst::SmHsmTst::SM} ................................................*/
QState SmHsmTst_initial(SmHsmTst * const me) {
    /*${smhsmtst::SmHsmTst::SM::initial} */
    printf("top-INIT.\n");
    return Q_TRAN(&SmHsmTst_s2);
}

/*${smhsmtst::SmHsmTst::SM::s} .............................................*/
QState SmHsmTst_s(SmHsmTst * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${smhsmtst::SmHsmTst::SM::s} */
        case Q_ENTRY_SIG: {
            printf("s-ENTRY.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s} */
        case Q_EXIT_SIG: {
            printf("s-EXIT.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::initial} */
        case Q_INIT_SIG: {
            printf("s-INIT.\n");
            status_ = Q_TRAN(&SmHsmTst_s11);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::I} */
        case I_SIG: {
            /*${smhsmtst::SmHsmTst::SM::s::I::[me->foo]} */
            if (me->foo) {
                me->foo = 0U;
                printf("s-I.\n");
                status_ = Q_HANDLED();
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::E} */
        case E_SIG: {
            printf("s1-E.\n");
            status_ = Q_TRAN(&SmHsmTst_s11);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${smhsmtst::SmHsmTst::SM::s::s1} .........................................*/
QState SmHsmTst_s1(SmHsmTst * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${smhsmtst::SmHsmTst::SM::s::s1} */
        case Q_ENTRY_SIG: {
            printf("s1-ENTRY.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1} */
        case Q_EXIT_SIG: {
            printf("s1-EXIT.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::initial} */
        case Q_INIT_SIG: {
            printf("s1-INIT.");
            status_ = Q_TRAN(&SmHsmTst_s11);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::I} */
        case I_SIG: {
            printf("s1-I.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::B} */
        case B_SIG: {
            printf("s1-B.\n");
            status_ = Q_TRAN(&SmHsmTst_s11);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::A} */
        case A_SIG: {
            printf("s1-A.\n");
            status_ = Q_TRAN(&SmHsmTst_s1);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::F} */
        case F_SIG: {
            printf("s1-F.\n");
            status_ = Q_TRAN(&SmHsmTst_s211);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::C} */
        case C_SIG: {
            printf("s1-C.\n");
            status_ = Q_TRAN(&SmHsmTst_s2);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::D} */
        case D_SIG: {
            /*${smhsmtst::SmHsmTst::SM::s::s1::D::[!me->foo]} */
            if (!me->foo) {
                me->foo = 1U;
                printf("s1-D.\n");
                status_ = Q_TRAN(&SmHsmTst_s);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&SmHsmTst_s);
            break;
        }
    }
    return status_;
}

/*${smhsmtst::SmHsmTst::SM::s::s1::s11} ....................................*/
QState SmHsmTst_s11(SmHsmTst * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${smhsmtst::SmHsmTst::SM::s::s1::s11} */
        case Q_ENTRY_SIG: {
            printf("s11-ENTRY.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::s11} */
        case Q_EXIT_SIG: {
            printf("s11-EXIT.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::s11::H} */
        case H_SIG: {
            printf("s11-H.\n");
            status_ = Q_TRAN(&SmHsmTst_s);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::s11::D} */
        case D_SIG: {
            /*${smhsmtst::SmHsmTst::SM::s::s1::s11::D::[me->foo]} */
            if (me->foo) {
                me->foo = 0U;
                printf("s11-D.\n");
                status_ = Q_TRAN(&SmHsmTst_s1);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s1::s11::G} */
        case G_SIG: {
            printf("s11-G.\n");
            status_ = Q_TRAN(&SmHsmTst_s211);
            break;
        }
        default: {
            status_ = Q_SUPER(&SmHsmTst_s1);
            break;
        }
    }
    return status_;
}

/*${smhsmtst::SmHsmTst::SM::s::s2} .........................................*/
QState SmHsmTst_s2(SmHsmTst * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${smhsmtst::SmHsmTst::SM::s::s2} */
        case Q_ENTRY_SIG: {
            printf("s2-ENTRY.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2} */
        case Q_EXIT_SIG: {
            printf("s2-EXIT.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::initial} */
        case Q_INIT_SIG: {
            printf("s2-INIT.\n");
            status_ = Q_TRAN(&SmHsmTst_s211);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::I} */
        case I_SIG: {
            /*${smhsmtst::SmHsmTst::SM::s::s2::I::[!me->foo]} */
            if (!me->foo) {
                me->foo = 1U;
                printf("s2-I.\n");
                status_ = Q_HANDLED();
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::C} */
        case C_SIG: {
            printf("s2-C.\n");
            status_ = Q_TRAN(&SmHsmTst_s1);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::F} */
        case F_SIG: {
            printf("s2-F.\n");
            status_ = Q_TRAN(&SmHsmTst_s11);
            break;
        }
        default: {
            status_ = Q_SUPER(&SmHsmTst_s);
            break;
        }
    }
    return status_;
}

/*${smhsmtst::SmHsmTst::SM::s::s2::s21} ....................................*/
QState SmHsmTst_s21(SmHsmTst * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21} */
        case Q_ENTRY_SIG: {
            printf("s21-ENTRY.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21} */
        case Q_EXIT_SIG: {
            printf("s21-EXIT.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21::initial} */
        case Q_INIT_SIG: {
            printf("s21-INIT.\n");
            status_ = Q_TRAN(&SmHsmTst_s211);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21::G} */
        case G_SIG: {
            printf("s21-G.\n");
            status_ = Q_TRAN(&SmHsmTst_s1);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21::A} */
        case A_SIG: {
            printf("s21-A.\n");
            status_ = Q_TRAN(&SmHsmTst_s21);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21::B} */
        case B_SIG: {
            printf("s21-B.\n");
            status_ = Q_TRAN(&SmHsmTst_s211);
            break;
        }
        default: {
            status_ = Q_SUPER(&SmHsmTst_s2);
            break;
        }
    }
    return status_;
}

/*${smhsmtst::SmHsmTst::SM::s::s2::s21::s211} ..............................*/
QState SmHsmTst_s211(SmHsmTst * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21::s211} */
        case Q_ENTRY_SIG: {
            printf("s211-ENTRY.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21::s211} */
        case Q_EXIT_SIG: {
            printf("s211-EXIT.\n");
            status_ = Q_HANDLED();
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21::s211::H} */
        case H_SIG: {
            printf("s211-H.\n");
            status_ = Q_TRAN(&SmHsmTst_s);
            break;
        }
        /*${smhsmtst::SmHsmTst::SM::s::s2::s21::s211::D} */
        case D_SIG: {
            printf("s211-D.\n");
            status_ = Q_TRAN(&SmHsmTst_s21);
            break;
        }
        default: {
            status_ = Q_SUPER(&SmHsmTst_s21);
            break;
        }
    }
    return status_;
}
/*$enddef${smhsmtst::SmHsmTst} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
